//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furnitura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furnitura()
        {
            this.FurnituraIzdeliyas = new HashSet<FurnituraIzdeliya>();
            this.SkladFurnituries = new HashSet<SkladFurnitury>();
        }
    
        public string Articul { get; set; }
        public string Naimenovanie { get; set; }
        public int Tip { get; set; }
        public decimal Shirina { get; set; }
        public Nullable<decimal> Dlina { get; set; }
        public Nullable<decimal> Ves { get; set; }
        public string Izobrazhenie { get; set; }
        public decimal Zena { get; set; }
    
        public virtual TipFurnitury TipFurnitury { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FurnituraIzdeliya> FurnituraIzdeliyas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladFurnitury> SkladFurnituries { get; set; }
    }
}
