//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izdelie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Izdelie()
        {
            this.ZakazannieIzdeliyas = new HashSet<ZakazannieIzdeliya>();
            this.Rulons = new HashSet<Rulon>();
            this.Tkans = new HashSet<Tkan>();
        }
    
        public string Articul { get; set; }
        public string Naimenovanie { get; set; }
        public int Shirina { get; set; }
        public int Dlina { get; set; }
        public string Izobrazhenie { get; set; }
        public string Commentariy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakazannieIzdeliya> ZakazannieIzdeliyas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rulon> Rulons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tkan> Tkans { get; set; }
    }
}
