//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rulon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rulon()
        {
            this.Izdelies = new HashSet<Izdelie>();
        }
    
        public string Articul { get; set; }
        public int Sostav { get; set; }
        public int Cvet { get; set; }
        public int Shirina { get; set; }
        public int Dlina { get; set; }
    
        public virtual Cvet Cvet1 { get; set; }
        public virtual MaterialSostav MaterialSostav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izdelie> Izdelies { get; set; }
    }
}
