//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkladFurnitury
    {
        public string KodPartii { get; set; }
        public string ArticulFurnitury { get; set; }
        public Nullable<int> Kolichectvo { get; set; }
    
        public virtual Furnitura Furnitura { get; set; }
    }
}
