//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkladTkani
    {
        public int KodRulona { get; set; }
        public string ArticulTkani { get; set; }
        public Nullable<int> Shirina { get; set; }
        public Nullable<int> Dlina { get; set; }
    
        public virtual Tkan Tkan { get; set; }
    }
}
