//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tkan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tkan()
        {
            this.FurnituraIzdeliyas = new HashSet<FurnituraIzdeliya>();
            this.SkladTkanis = new HashSet<SkladTkani>();
            this.MaterialSostavs = new HashSet<MaterialSostav>();
            this.Izdelies = new HashSet<Izdelie>();
        }
    
        public string Articul { get; set; }
        public string Naimenovanie { get; set; }
        public Nullable<int> KodCvet { get; set; }
        public Nullable<int> KodRisunok { get; set; }
        public int Shirina { get; set; }
        public int Dlina { get; set; }
        public decimal Zena { get; set; }
        public string Izobrazhenie { get; set; }
    
        public virtual Cvet Cvet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FurnituraIzdeliya> FurnituraIzdeliyas { get; set; }
        public virtual Risunok Risunok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladTkani> SkladTkanis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSostav> MaterialSostavs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izdelie> Izdelies { get; set; }
    }
}
