//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazannieIzdeliya
    {
        public int NomerZakaza { get; set; }
        public string ArticulIzdeliya { get; set; }
        public string Kolichestvo { get; set; }
    
        public virtual Izdelie Izdelie { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
